### ISSUE TITLE
Error when using footnotes extension with combined option

### ISSUE THREAD

**Issue by Jaykju** [zhaoterryy/mkdocs-pdf-export-plugin#38]
I am trying to export my docs to a single PDF using the combined option while having the footnotes extension enabled:

```yaml
markdown_extensions:
    - footnotes
    # more config

plugins:
    - pdf-export:
          combined: true
```

If I disable the combined option everything works fine. But as soon as I enable it I get the following error for every file that I use footnotes in:

```
":" and "/" characters are banned! /:
Error converting folder/file.md to PDF: Invalid ID found in folder/file/, ID: fnref:linkname
```

Any help would be appreciated.
